name = "Dokun Digital"
license = "MIT"
licenselink = "https://github.com/themefisher/bigspring-hugo-startup-theme/blob/master/LICENSE"
description = "Toko Online Produk Virtual Terpercaya !"
homepage = "https://dokundigital.com"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography', 'multilingual', 'gethugothemes']
features = ['bootstrap','responsive']
min_version = "0.64.0"

[author]
name = "Themefisher & dokun"
homepage = "https://dokundigital.com/"