---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/english/contact
  label: Contact
  create: all
  match: "**/*"
- type: heading
  label: Konten
- type: directory
  path: content/english/produk
  label: Produk
  create: all
  match: "**/*"
- type: directory
  path: content/english/blog
  label: Blog
  create: all
  match: "**/*"
- type: heading
  label: Halaman
- type: directory
  path: content/english/privacy-policy
  label: Privacy
  create: all
  match: "**/*"
- type: directory
  path: content/english/terms-condition
  label: Terms
  create: all
  match: "**/*"
- type: directory
  path: content/english/faq
  label: FAQ
  create: all
  match: "**/*"
- type: directory
  path: content/english
  label: All Page
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.74.3
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.74.3
